# Generated by Django 4.2.1 on 2023-05-04 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
