# Generated by Django 4.2.1 on 2023-05-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_date_book_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_drama',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_novel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_scifi',
            field=models.BooleanField(default=False),
        ),
    ]
